name: Test-Input-Ouput-Use-Orther-Action
run-name: just one test of the mean that the name
inputs:
  msg_a:
    description: 'this is msgA'
    require: true
  msg_b:
    description: 'this is msgB'
    require: false
    default: 'msgB'
outputs:
  result_a: 
    description: 'this is resultA'
    value: 'resultA'
  result_b: 
    description: 'this is resultB'
    value: 'resultB'
    
jobs:
  say_hello:
    steps:
      - name: say_hello
        shell: bash
        id: hello
        run: |
          echo "hello msgA"
          echo "::set-output name=result_a::xxx"
        
      - name: say_world
        shell: bash
        id: world
        run: echo "hello msgB"
