name: Test-Input-Ouput-Use-Orther-Action

author: Heachy

description: One test for creating action into market. Input some args and return something


inputs:
    msg_a:
        description: 'this is msgA'
        require: true
    msg_b:
        description: 'this is msgB'
        require: false
        default: 'msgB'
outputs:
    result_a: 
        description: 'this is resultA'
        value: 'resultA'
    result_b: 
        description: 'this is resultB'
        value: 'resultB'
runs:
    using: "composite"
    steps:
        - name: Run script
          shell: bash
          run: ${{GITHUB_ACTION_PATH}}/script.sh
          env:
              INPUT_MSG_A: ${{ inputs.msg_a }}
              INPUT_MSG_B: ${{ inputs.msg_b }}
    
branding:
  icon: 'book-open'
  color: 'blue'
