# 链接服务器并执行命令的workflow

name: SSH-Connect
run-name: update the repository of server

# 当有push和pr在main分支时，执行
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # 允许手动执行
  workflow_dispatch:

# 工作流
jobs:
  # 任务名
  update-server:
    # 需要的运行环境
    runs-on: ubuntu-latest

    # 任务流程
    steps:
      # 检出仓库
      - uses: actions/checkout@v3 # 拉取更新repository
      - name: pull repository
        uses: garygrossgarten/github-action-ssh@release # ssh链接服务器
        with: 	# 参数配置以及执行的命令
          command: |
            cd /www/wwwroot/heachy.com/TestForDocsify
            git pull
          host: ${{ secrets.HOST }}
          username: root
          privateKey: ${{ secrets.PRIVATE_KEY}}
