name: Test the action of my created in the repository


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test-my-action:
    uses: ./.github/workflows/Workflow-Test.yml
    with: 
      msg_a: 'hello'
      msg_b: 'world'
  print-something:
    runs-on: ubuntu-latest
    needs: test-my-action
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: use the outputs
        run: |
          echo "The resultA is ${{ needs.test-my-action.outputs.result_a }}"
          echo "The resultA is ${{ needs.test-my-action.outputs.result_b }}"
      - name: The End
        run: echo Hello,My Action!
