name: Test-Input-Ouput-Use-Orther-Action
run-name: just one test of the mean that the name
on:
    workflow_call:
        inputs:
            msg_a:
                description: 'this is msgA'
                type: string
                required: true
            msg_b:
                description: 'this is msgB'
                required: false
                type: string
                default: 'msgB'
        outputs:
            result_a: 
                description: 'this is resultA'
                value: 'resultA'
            result_b: 
                description: 'this is resultB'
                value: 'resultB'
    
jobs:
    say_hello:
        runs-on: ubuntu-latest
        steps:
        - name: say_hello
          id: hello
          run: |
            echo "hello msgA:${{ inputs.msg_a }}"
            echo "::set-output name=result_a::${{ inputs.msg_a+'resultA' }}"
          
        - name: say_world
          id: world
          run: echo "hello msgB:${{ inputs.msg_b }}"
